name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Check for warnings
      run: cargo check --all-targets --all-features

    - name: Run tests
      run: cargo test --all-targets --features testing

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D clippy::all
